version: "3.9"

services:
    app:
        env_file:
            - .env
        container_name: iot-deployment-platform
        image: iot-deployment-platform
        build:
            context: .
        ports:
            - 8080:8080
